### ISSUE TITLE
Docstrings for functions

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#127]
To begin with, this requires that #126 is done. This is because I plan to attach a method to all functions that looks like this: `define doc[A > function](A => string)`. All functions, including built-in ones, will be able to have docstrings associated with them.

Here is an example of different docstrings:

```
class Point(x: integer, y: integer)
"""
This class represents a two-dimensional point.
The constructor requires two values:
* The x coordinate (an integer)
* The y coordinate (an integer)
"""

var @x = x
var @y = y

    define copy( => Point)
    """
    Constructs a copy of the Point given.
    """
    {
        return Point::new(@x, @y)
    }
}

# Lily doesn't allow classes as values like Python.
# Instead, the docstring is bound to the ::new of a class.
Point::new.doc()

Point::copy.doc()
```

Later on, I could easily write a 'help' command that would print a function's docstring to the console, ala Python.

**Comment by jesserayadkins** [comment]
Going to wait until #231 (the Unit type) lands, so that I can write it as `Function.doc(Function(~1):Unit)`, thus making it a method available upon any `Function`.
