### ISSUE TITLE
Have a 'self' return type, and strongly suggest usage of it.

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#138]
This is inspired partly from seeing it in Hack, and in inspecting some of Scala's api.

In Hack, a class method can return self to indicate that it's giving back the same type that is put into it. On the face of it, this might seem to be something that's neat, but not very useful. I think it's a neat feature, especially because of the growing importance of type inference in Lily.

```
class Container[A](start: A) {
    var @contents = [start]

    define add(value: A => Container[A]) {
        ...
    }
}

class SuperContainer[A](start: A) < Container(start) {
    define inspect() {
        ...
    }
}
```

And then you try to do something like this:

```
var v = SuperContainer::new(1).add(2)
```

Lily's perfectly capable of making an emit-time decision that, yes, what was passed as the first argument to the add function should be what comes out of it. But it doesn't, because the type system doesn't currently allow for that. So, instead, you get a regular container. This is bad, because it harms type inference. It's even worse if, say, SuperContainer was somehow more generic than Container.

This calls for a couple of things:

One, allowing 'self' to appear within the return of a class method that takes an instance of the class as the first parameter. I say it like this, because File::open is the only static method that I can think of off the top of my head, and this wouldn't apply to that. I also don't want to force self if, say, the input is SomeType\[A\] and the result is SomeType\[B\]. self wouldn't be allowed in normal declarations, classes, or anything else.

Secondly, that if a method DOES want to return something that is exactly the same as itself, it can do so by including an exclamation mark. This would not be included in the resulting type, but is instead a hint that 'yes, I really mean to return this'. Examples of this could be a `list::foldLeft` function, where the intent is to allow the type of A to degrade through unification (note: This is not yet implemented). This would result in giving back the most useful 'A' in the event that folding returns some lower class than the input.

By strongly suggesting this, it has the added benefit of making classes more useful: I can easily write classes that inherit others that use self, and not have to worry about degrading of types (such as in the above example), because the language forces the author to either use 'self' as the return, or explicitly say that is what they want with an added '!'.

**Comment by jesserayadkins** [comment]
Punting this to the next release because the current one has taken too long as it is. This also doesn't provide any solid value right now, seeing as there's no Lily code aside from what's in the tests.
