### ISSUE TITLE
Allow match cases to use _ to skip decomposition

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#158]
```
define is_some(v: Option[Integer]): Boolean
{
    match v: {
        case Some(s):
            return true
        case None:
            return false
    }
}
```

In a situation like this (no, this isn't how it's done internally), there's no reason to name `s`, since it used anywhere. I'd like to make it so that using `_` is a special case, wherein the match decomposition will be ignored.

Given how Lily is designed, one way of doing this is having parser say that the variable id to decompose to is something invalid (-1, for example). Emitter picks up on that, and instead grabs a storage to fill that spot. By doing so, the user can use `_` repeatedly to ignore naming targets that are of no use.

There are probably optimizations that could be done on top of this. But, for now, I'm only concerned about the user-facing syntax of being able to use `_` to skip decomposition.

It is assumed that the user won't want to name a variable `_`, so checking for a supplied name of `_` is sufficient.

**Comment by stevedonovan** [comment]
I was immediately able to get rid of a lot of lines in my json module ;)

**Comment by FascinatedBox** [comment]
Neat! I didn't realize it would be that useful.
