### ISSUE TITLE
Update Rosetta code's examples

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#163]
I wrote the existing Rosetta code examples a while back. I'm quite certain that most of them won't work in the current version of Lily. Given that there aren't many of them, it would be a relatively easy task to go through and update them to work in the current version. Most of the breakage is probably titlecasing built-in types, changing how returns are denoted, and adding interpolation. Given that there's a small number of easy examples ( < 100 lines total, between less than 20 examples), this wouldn't be that difficult. This would help the language by making sure that non-working examples are not someone's first introduction to the language.

**Comment by gernest** [comment]
@jesserayadkins I cant find any link to this, could you provide them for me?

**Comment by jesserayadkins** [comment]
Oh, sorry about that. The examples can be found here: http://rosettacode.org/wiki/Category:Lily

**Comment by gernest** [comment]
@jesserayadkins :+1:  wondering if you will be hanging at gitter, maybe to chat abit about lily( I am enjoying ipalyning with lily so far)

**Comment by FascinatedBox** [comment]
Closing this since I've just now finished touching up the examples that I put in.
