### ISSUE TITLE
Time Module

### ISSUE THREAD

**Issue by willzfarmer** [FascinatedBox/lily#169]
Currently there is no code that provides time functionality, such as system time, UTC, etc. Adding a timing module would provide core functionality as well as potentially help solve issues such as #167 by having an initial seed always available.

Potential functions include
- Current Processor Time
- Current Epoch Time
- Sleep
- etc.

**Comment by jesserayadkins** [comment]
This would be useful for benchmarks. I probably won't get to it soon though, as I'd like to see what other languages provide, and where I'd want a time module to fit.

**Comment by FascinatedBox** [comment]
Right now I'm trying to clear the lower numbered bugs, since they've been hanging on for a while. I'll add a handful of time-related functions for now in a time package. It won't be much, but enough to be useful, and a base on which to build from for 1.1 and beyond.
