### ISSUE TITLE
Replace abysmal hash internals with something better

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#179]
I ran a few benchmarks on Lily recently. Most seem promising, but there was one that stuck out. One test that did a lot of insertions on hash tables was far, far slower on Lily than any other interpreted language that I tested. Rather than try to fix Lily's hash tables (I'm not very attached to them), I instead plan to use Peter Moore's st.c hash implementation, after some modifications.

This will be done as part of #175, since mod_lily will need to be able to do hash creation.

**Comment by jesserayadkins** [comment]
I'm removing this from the milestone because it's just too much to do all at once. I'd rather have a fresh cycle and have the time to do this right.
