### ISSUE TITLE
Does Lily provide a REPL?

### ISSUE THREAD

**Issue by akavel** [FascinatedBox/lily#195]
I don't recall seeing any mention of such on the website, so I assume the answer is "No", but wanted to clarify. TIA!

**Comment by jesserayadkins** [comment]
Not yet. Currently, if you execute the interpreter and it fails, the interpreter's state is a total tossup. In order for a repl, Lily first needs to do rewinding #174. I need to finish the api too, because there's currently no way to just send Lily a chunk instead of a whole file/whole string.

**Comment by akavel** [comment]
Thanks for the response! I'd be happy to know once a REPL becomes available, if that happens at some point.

**Comment by FascinatedBox** [comment]
I've added a lily-repl repository with a repl. The repl is very basic (it reads directly from stdin, so there's no arrow key support or history). You'll need the absolute latest interpreter (bfa9541), and to use garden to install `spawni` to get it working. But basics like running commands for results and defining classes work.

**Comment by stevedonovan** [comment]
Most cool! I'll look at doing a readline or linenoise extension...
