### ISSUE TITLE
Question about lambdas and |> operator

### ISSUE THREAD

**Issue by radiofreejohn** [FascinatedBox/lily#210]
The tutorial says that functions with only a lambda as an argument can be called without parenthesis.

I would have expected that these two would be the same:
```
[1, 2, 3].each{|e| print(e) }
{|e| print(e)} |> [1,2,3].each
```

This gives an error `SyntaxError: Unexpected token a lambda.` in the sandbox.

This works fine though, as expected:
```
({|e| print(e)}) |> [1,2,3].each
```

**Comment by jesserayadkins** [comment]
Huh, strange. Smells like it's a parser bug, hopefully. I'll take a poke at it later.
