### ISSUE TITLE
Change of style guide

### ISSUE THREAD

**Issue by azbshiri** [FascinatedBox/lily#215]
When I was reading the source code I've reached to how functions are written, some of them were small and nothing special but others had return types which is hard to read and it'd be better if you change the style guide to write function return types in a separate line. Also after that it's possible to grep based on function names and I'd would recommend to use [Allman style](https://en.wikipedia.org/wiki/Indent_style#Allman_style) + return type in separate line.

**Comment by azbshiri** [comment]
@jesserayadkins

**Comment by jesserayadkins** [comment]
I'm really hesitant to make any decisions regarding style right now, as my mind is more geared toward cleaning the core and getting an api pushed out. I worry that trying to do this now might result in me regretting the decision later on.

That said, I see some appeal toward longer functions having their return on a different line.

**Comment by FascinatedBox** [comment]
Since the next release is likely to be 1.0, I think this should be addressed. Going to say no to this, because I like Lily's style as it is.
