### ISSUE TITLE
Add environment variables to standard library

### ISSUE THREAD

**Issue by nwjlyons** [FascinatedBox/lily#216]
Hi Jesse, I really like what you have done with Lily. 

I'd like to get access to environment variables in the language. I'm not a C programmer but was playing around with adding [`char **envp`](http://crasseux.com/books/ctutorial/Environment-variables.html) as the third argument to the `main` function. That gets what I'm after. Then it is just a matter of converting that array to a Lily `Hash[String, String]` type. 

What are your thoughts? Have you got any ideas how best to implement this and which library to add it too? I was thinking `sys.env` but I know python has environment variables in the `os` module and command line arguments in the `sys` module.

**Comment by jesserayadkins** [comment]
Thanks!

I like the thought of Lily getting access to environment variables. I have some thoughts:

There should be a fallback, just as there is for `sys.argv`. I think that, for example, mod_lily should not bother providing environment variables.

#179 should be taken care of before this, or it will have to be rewritten for the new api.

Strings are supposed to be valid utf-8, so can environment variables have names and/or values that are invalid utf-8?

Given that this would either alter `sys` or create a new package, I hesitate to do this now. I'd like to do this some time later in the next release, when I've got time to really think about where I want the environment.

**Comment by stevedonovan** [comment]
I think this is exactly the time to experiment with the API, before there are zillions of users. I remember working with early Go, building from source, and people understand that new languages take a while to settle. NB to provide some interesting functionality so people can write real scripts that satisfy their need for a solution.

While thinking about `sys`, I'd even say that what a programmer needs is `sys.args`, i.e. not including the first argument passed (can call that `sys.prog` or something). Time to break away from Python ;)

So, why not `sys.getenv(String): Option[String]`? It would be very odd to put non-text in an environmental variable, and if so this will just fail.

**Comment by jesserayadkins** [comment]
I'd still like some way of getting all of the environment variables, if there's a possible and portable way to go about doing it. But, failing that, I really like your idea of `getenv` pushing back an Option to handle the unlikely case of invalid utf-8. It feels right to me.

I hesitate to touch `sys.argv` at the moment though. Too much else on my mind right now.

**Comment by stevedonovan** [comment]
Fair enough!  But why the need to get all the environment variables? It seems a waste if the person just wants to look up "HOME".

**Comment by stevedonovan** [comment]
(`getenv` would also return `None` if the variable was not found. Edge case opens where funny variable is simply 'not seen')

**Comment by jesserayadkins** [comment]
Someone might want to iterate over environment variables to print them all out? Probably a limited case for that, come to think of it. But the getenv call is easier to reason about: It calls system getenv, and returns None if the string is invalid utf-8 or the item isn't found.
