### ISSUE TITLE
Default case for enum match

### ISSUE THREAD

**Issue by stevedonovan** [FascinatedBox/lily#225]
It would be most convenient, and more efficient, to have a default case for long matches. For example, here's part of a `JsonObject` enum:

```C
enum JsonObject {
    JS(String)
    JN(Double)
    JA(JsonObject...)
    JO(Hash[String,JsonObject])
   ....
    define as_number(def: Double): Double {
       match self: {
       case JN(n): return n
       case JS(n): return def
       case JA(n): return def
       case JO(n): return def
       }
    }
    ...
```

So if there was an `else` clause, things get much neater, especially when there are even more variant values.

**Comment by jesserayadkins** [comment]
Agreed. Goes in hand with allowing _ to skip decomposition.
