### ISSUE TITLE
Is there a short guide for embedding it into another program?

### ISSUE THREAD

**Issue by vonHabsi** [FascinatedBox/lily#228]
From looking at lily.c it seems that having a lily_parse_state, a lily_lex_mode and passing the code to lily_parse_string is all it takes. Do you have a simple example available, as well as one in which it is used as a dynamic library? C is not one of my strengths.

Is to_process the actual string passed to lily, ie the contents of the string or the file?

**Comment by jesserayadkins** [comment]
At the moment, no. Some of those functions will be changing when the api is done, and also I'll put some documentation up too.

If you're parsing a file, to_process is the filename. If you're parsing a string, to_process is the whole string to be processed.

**Comment by FascinatedBox** [comment]
I've updated the website, and included are a few examples of how to embed/extend the language, along with api documentation: lily-lang.org/embed_and_extend.html
