### ISSUE TITLE
Function pipe with partial arguments

### ISSUE THREAD

**Issue by mlajtos** [FascinatedBox/lily#271]
Hello :)

I was really glad to find out that you implemented a function pipe. I have a simple question about it. How would you write something like this?
```lily
"Hello World" |> String.split |> List.join("&") |> print
```

**Comment by beyondred** [comment]
`("Hello World" |> String.split).join("&") |> print`

Like so. You want to not pipe, but method call to carry over the `List` to do the join.

**Comment by mlajtos** [comment]
I was hoping for a pure pipe solution. Does that mean pipes in Lily are strictly for single argument functions? What about wrapping it with lambda like this:
```lily
"Hello World" |> String.split |> {|list: List| List.join(list, "&")} |> print
```

**Comment by FascinatedBox** [comment]
> Does this mean that pipes in Lily are for single argument functions.

Yep.

Your solution works if you qualify the `:List` as `:List[String]`, by the way.

**Comment by mlajtos** [comment]
> Your solution works if you qualify the ```:List``` as ```:List[String]```, by the way.

Ah, thank you for pointing out the error. I was confused by the error message – "Expected '[', not '|'" – I thought it meant the first "|", not the second.

> Yep.

OK. Thank you for your time. :)

**Comment by FascinatedBox** [comment]
> I was confused by the error message.

I noticed that too. Should mention that List isn't fully qualified. List of what? When I get a spark of interest in this again, I'd like to fix that. Thanks.

**Comment by stevedonovan** [comment]
In an ideal universe, that lambda would be able to infer that it was passed a `List[String]`. So 

      ... |> {|ls| ls.concat(",") } ...

I must say that local type inference really makes static languages come alive again!

**Comment by FascinatedBox** [comment]
It's possible, but difficult. Something that I've admittedly been aware of for a while, but haven't yet addressed. Fixing it would entail redoing some of the wiring around sending a call down to a lambda. Giving it a way to say "You get these arguments, what do you produce?". I think that would be better off until after `Unit` lands though. Less questions about what a lambda means to return: Does it mean to return nothing, or is it just not sure of the caller wants something?
