### ISSUE TITLE
Register 'lily-lang.org' (or settle on a URL)

### ISSUE THREAD

**Issue by jonathonf** [FascinatedBox/lily#272]
Over the past week the website and git repo have been renamed three times.

I suggest two alternatives:
1. Register 'lily-lang.org' and use that as the canonical site domain (then it doesn't matter what the underlying github.io site is).
2. Settle on a name!

**Comment by FascinatedBox** [comment]
Yeah, sorry about all the change. I was more picky about choosing this name, and I don't have any intention of changing it again, without an exceptionally good reason. You've got a point about registering a site though. I bought lily-lang.org a while back, but I never got around to fixing it to point at anything. I just use it for a custom e-mail address.

**Comment by jonathonf** [comment]
Ah, that's good to hear!

IIRC it's possible to use a custom domain for the github.io site, or you could just forward lily-lang.org to the current URL.

**Comment by FascinatedBox** [comment]
Wrong number, sorry about that. A while back, I had the site up and working (and pointing to my GH page, good idea by the way). More recently, I went to test the site, and it's down. I'll look into fixing the domain later.

**Comment by FascinatedBox** [comment]
This took far longer than it should have, but I think I fixed it for good this time. Now, `lily-lang.org` points directly at `fascinatedbox.github.io/lily`, and forwarding is enabled. A neat side-effect of this, that I hadn't previously considered, is that the fixed url looks more official. Thanks! :)
