### ISSUE TITLE
[ANN] lily-extras

### ISSUE THREAD

**Issue by stevedonovan** [FascinatedBox/lily#274]
I've put my Lily work in progress into this repo:

https://github.com/stevedonovan/lily-extras

Some useful extensions, and examples of non-trivial Lily code

**Comment by FascinatedBox** [comment]
This is very impressive. This is the first time I've seen so much Lily code at once, so it's, I had to take a step back and just admire that the interpreter has come so far. I'm particularly impressed by skelgen. You mentioned that to me once before, but I could never quite grasp what it did. I like it.

**Comment by stevedonovan** [comment]
It's an actually useful program!  So with a bit of library love, Lily is very capable.

**Comment by FascinatedBox** [comment]
I've added a link to community packages at the end of the readme (it's in the site now too) and I've added your links to it. Closing this.
