### ISSUE TITLE
Allow Hack-inspired shorthand constructors.

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#278]
`class Point(@x: Integer, @y: Integer) { ... }`

Much better than creating 'x' and then assigning `@x` to `@y` for example. Really tired of seeing the duplicated work. People who use this should, however, understand that the ordering of arguments becomes important (and they should not be changed).

**Comment by FascinatedBox** [comment]
Fixed by 951c38a. The syntax is to use `var @<name>` instead of simply `@<name>` so that intent is clear and distinct.

**Comment by stevedonovan** [comment]
That's a much nicer syntax. Would be a good idea to update the tutorial and mention this.

**Comment by FascinatedBox** [comment]
Thanks! I completely forgot that. Fixed it just now.
