### ISSUE TITLE
Rewrite Lily in Rust

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#294]
After 5 years of having Lily in Rust and rewriting it in C over the course of a month, I'm starting to heavily regret my decision. I've had several developers say they're no longer interested in the project, and a person knocked on my door a few minutes ago to ask if I had heard the good news. I'm really scared because he had a Rust book in his hand and there was a scary man with him.

But I've really screwed up. When I rewrote Lily, I did it by rebasing the entire tree. I went back to the beginning and I rewrote each Rust commit into C so I could keep the history of the project, but it would all be in C instead of Rust. I need that history instead of one large blob because it means a lot to me.

I'm sorry for what I've done. I now understand the importance of Rust. I miss it so much, please forgive me. I miss these things.

* zero-cost abstractions
* move semantics
* guaranteed memory safety
* threads without data races
* trait-based generics
* pattern matching
* type inference
* minimal runtime
* efficient C bindings

**Comment by bstrie** [comment]
Fear not, my child. Rust is merciful, and shall grant forgiveness for those who seek it. As penance for your transgressions, triage ten bugs on the issue tracker, and recite thrice on the Rustary. Now, join me in prayer:

*Our language,* 
*Who art on GitHub,* 
*Hallowed be thy `git blame`.* 
*Thy rewrite come,* 
*Thy will be done,* 
*Online as it is in heaven.* 
*Give us this day our zero-cost abstractions,* 
*And forgive us our allocations,* 
*As we forgive those who allocate unavoidably.* 
*Lead us not into unsafety,* 
*And deliver us from C-vil.*

Now go, my child. Go in the grace of Rust.

**Comment by FascinatedBox** [comment]
Yes, yes, a prayer. That's exactly what I need. Praise be to Rust. Hail Rust, for being so merciful. Deliver me from C-vil. Thank you, thank you thank you good person.

Yes, I have heard the good news today.

**Comment by FascinatedBox** [comment]
I was eating lunch today at work and one of the people I work with is a C compiler developer. He took my lunch money and said he would only give it back if I closed this issue. I'm really thirsty for chocolate milk right now so...
