### ISSUE TITLE
match for user-defined classes

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#304]
A long time ago, I put in a special syntax for extracting the contents of a `Dynamic` out. It's a funky `.@(type)`, and I hardly ever use it now. However, I never put in syntax to allow for doing that kind of cast onto a class. Part because it would involve a new runtime opcode, and part because I wasn't sure I wanted to do it that way.

What I'd like to do is to extend `match`, so that the input sym can be a user-defined class. Example:

```
class Base {}
class Left < Base {}
case Right < Base {}

var v: Base = Right()

match v: {
    case Left(l):
    case Right(r):
    else:
}
```

Rules:

Since users can't control the open-ness of their classes, I think it's unfair to have an exhaustiveness check, because their classes may be extended from a far away place. Instead, I think matching upon a user-defined class should instead require that there is an `else` clause.

Polymorphic classes will not have this available to them. If, for example, `Left` was defined as having some generic, then that generic couldn't be filled based on `Base` because it doesn't exist. I may later relax this to allow it if the generic counts are equal. But I think the more important goal is that this works for more simple classes which I think are more likely to need it.

This will not work for `Dynamic`, though I may later make it work for `Dynamic` so that the `.@(type)` special-case syntax can be removed.

I plan to add a `with` block that mirrors the Rust-style `if let` block in the future as a shorthand for when a user is only interested in one particular enum or user class case.

**Comment by stevedonovan** [comment]
Very cute idea - it's much better than the usual `is_instance`.
