### ISSUE TITLE
Error in sample?

### ISSUE THREAD

**Issue by sauer2** [FascinatedBox/lily#344]
```
# Class properties and methods are public by default.
class Terminal(var @foreground: Color, width_str: String)
{
    public var @width = width_str.parse_i().unwrap_or(80)

    public define set_fg(new_color: Color) {
        @foreground = new_color
    }
}
```

How comes the example ones are explicitly marked as public? Shouldn't it be the other way around?

Also, the link to the languages website appears to 404.

**Comment by FascinatedBox** [comment]
Looks like I missed the comment when I changed how scoping works. Whoops. Also, I'll take a look at the website links.

**Comment by FascinatedBox** [comment]
Also, while cleaning out the lily-site repo, I accidentally nuked the sandbox. I was supposed to clean out everything but the sandbox. With that, I believe this is fixed, but if I missed something, feel free to reopen it.

Thanks for the heads up.
