### ISSUE TITLE
Build instructions for tests?

### ISSUE THREAD

**Issue by stevedonovan** [FascinatedBox/lily#367]
Building Lily is very straightforward, but building the tests is not obvious: `cmake .` in `test` folder breaks with 

    Objects of target "liblily_obj" referenced but no such target exists.

**Comment by FascinatedBox** [comment]
Running the tests is awkward. It's done through 'pre-commit-tests', which is an executable. I want to eventually make it running Lily as an executable to the main test script. But to do that, Lily needs to be able to exit, and I'm not entirely sure how I want to implement exiting yet.

For the time being, yes, the documentation should mention that.
