### ISSUE TITLE
World Heavy Weight Programming Language Championship contest is GOING DOWN!

### ISSUE THREAD

**Issue by polterguy** [FascinatedBox/lily#374]
I'm waiting for a reply from _"FascinatedBox"_ whether or not he is willing to meet me in a fair contest, organised and suggested by the moderators of the sub-reddit (/r/shittyprogramming).

[OK, let's do this!](https://gaiasoul.com/2018/05/20/ok-lets-do-this/)

The background for the contest was the [following posting at Reddit.com](https://www.reddit.com/r/shittyprogramming/comments/7q6jwv/hyperlambda_is_an_amalgamation_of_buzzwords_and/)

I have informed the whole world that I'll be participating, and I have spread the above link all over Social Media under the title of _"World Heavy Weight Programming Language Championship contest is GOING DOWN!"_ - I'll try to get Guinness World Book of Records to participate as a neutral observer. I assume we will both be given the same specification, and asked to solve the problem, any ways we see fit.

I have invited Microsoft, MSDN, Channel9, DZone, and several other _"heavy weights"_ from our industry to help promote and air the event.

I will be using exclusively Hyperlambda (if possible), and resort only to C# Active Events where I have to. OP can use any programming language, library, or framework he wants to - Including his own programming language called _"Lily"_.

Lily has 2622 commits to its Git repo, Phosphorus Five and hence Hyperlambda has 2901 commits, so both languages should be equally mature, and hence arguably belong to the same _"weight class"_.

Lily is an OOP language and Hyperlambda is (some would argue) a Functional Programming Language - Although technically this is not correct - So I guess it also would solve the dispute of _"OOP versus FP"_. As I have understood, the event will be streamed live, and any profits will go to charity. However, I am not acquainted with the organisers myself in any ways, and I know nothing about the event besides the screenshot in the above link. In addition, it provides the OP to put weight behind his statements about Hyperlambda, if he should win.

The loser will be banned from posting at [/r/shittyprogramming](https://www.reddit.com/r/shittyprogramming/) the way I have understood the rules, and the winner will be promoted by the moderators of the sub-reddit ...

I think I have taken this as a sport, and I wish _"FascinatedBox"_ good luck.

[Read more about Hyperlambda and Phosphorus Five here](https://github.com/polterguy/phosphorusfive)

May the best man win!

Thomas Hansen - The inventor of Hyperlambda ...

**Comment by polterguy** [comment]
I must say, I am impressed. I actually thought you were going to let me down! Regardless of how this ends up, I respect the fact that you were willing to meet me.

May the best man win ...!!

**Comment by FascinatedBox** [comment]
Haven't been checking on this repo like I should have been. Looking forward to the challenge. Have to agree, may the best win.

**Comment by polterguy** [comment]
Thx, I looked at your language too myself, and I am deeply impressed by your work. It takes a special kind of determination to do what we both do I think ... :)

I'll close this one to hide it, I wouldn't want to create the impression for the kids that we're not _"mortal enemies"_, that would destroy half the fun, right ...? ;)
