### ISSUE TITLE
Benchmarks don't work

### ISSUE THREAD

**Issue by brucehoult** [FascinatedBox/lily#378]
Benchmarks all fail with basically the same error:

    bruce@nuc:~/software/lily2$ ./lily test/benchmark/fib.lily 
    SyntaxError: Expected '{', not 'a label'.
        from test/benchmark/fib.lily:8:
    bruce@nuc:~/software/lily2$ ./lily test/benchmark/for.lily 
    SyntaxError: Expected '{', not 'a label'.
        from test/benchmark/for.lily:7:
    bruce@nuc:~/software/lily2$ ./lily test/benchmark/binary_trees.lily 
    SyntaxError: Expected '{', not 'a label'.
        from test/benchmark/binary_trees.lily:11:

**Comment by FascinatedBox** [comment]
Apologies for not getting back to you sooner on this. I've been migrating Lily over to gitlab, so I haven't checked back here in a while. It looks like I forgot to roll over the benchmarks for the "braces are now required" patch. I'll get to that now. The change will be in the gitlab repo though, and not here (I came here to turn off the lights, so to speak). The gitlab repos, btw, have the same paths as the one here.

**Comment by FascinatedBox** [comment]
Fixed over on gitlab: https://gitlab.com/FascinatedBox/lily/commit/c20272704b66b68705f09390ff17b011a2f94089
